/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.jsx',
        './resources/**/*.ts',
        './resources/**/*.tsx',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            colors: {
                "surface-bright": "#fcf9f8",
                "on-secondary-container": "#003869",
                "tertiary-fixed-dim": "#80d0ff",
                "surface-dark": "#171717",
                "surface-strong": "#f0f0f3",
                "surface-container-lowest": "#ffffff",
                "inverse-primary": "#c6c6c6",
                "sky-gradient-end": "#a8c8e8",
                "sky-gradient-start": "#cfe7ff",
                "on-secondary": "#ffffff",
                "surface-container-low": "#f6f3f2",
                "on-secondary-fixed-variant": "#004884",
                "primary-container": "#1b1b1b",
                "surface-dim": "#dcd9d9",
                "on-tertiary": "#ffffff",
                "secondary": "#005fad",
                "secondary-fixed": "#d4e3ff",
                "surface-container": "#f0eded",
                "inverse-surface": "#313030",
                "secondary-fixed-dim": "#a4c9ff",
                "on-surface-variant": "#4c4546",
                "on-tertiary-container": "#008dc1",
                "accent-warning": "#ab6400",
                "on-error-container": "#93000a",
                "on-primary-fixed": "#1b1b1b",
                "surface-container-high": "#eae7e7",
                "outline": "#7e7576",
                "error": "#ba1a1a",
                "tertiary": "#000000",
                "semantic-success": "#16a34a",
                "on-secondary-fixed": "#001c39",
                "on-background": "#1c1b1b",
                "primary-fixed-dim": "#c6c6c6",
                "primary": "#000000",
                "surface-variant": "#e5e2e1",
                "canvas": "#ffffff",
                "on-tertiary-fixed": "#001e2d",
                "on-error": "#ffffff",
                "on-primary-container": "#848484",
                "secondary-container": "#56a3ff",
                "on-surface": "#1c1b1b",
                "canvas-soft": "#fafafa",
                "primary-fixed": "#e2e2e2",
                "surface-tint": "#5e5e5e",
                "tertiary-container": "#001e2d",
                "on-primary": "#ffffff",
                "semantic-error": "#eb8e90",
                "surface": "#fcf9f8",
                "outline-variant": "#cfc4c5",
                "on-primary-fixed-variant": "#474747",
                "inverse-on-surface": "#f3f0ef",
                "ink-muted": "#999999",
                "error-container": "#ffdad6",
                "ink-body": "#60646c",
                "background": "#fcf9f8",
                "surface-container-highest": "#e5e2e1",
                "on-tertiary-fixed-variant": "#004c6a",
                "tertiary-fixed": "#c5e7ff"
            },
            fontFamily: {
                sans: [
                    'Figtree',
                    'Inter',
                    '-apple-system',
                    'system-ui',
                    'Segoe UI',
                    'Roboto',
                    'Helvetica',
                    'Arial',
                    'sans-serif',
                ],
                mono: [
                    'JetBrains Mono',
                    'ui-monospace',
                    'SFMono-Regular',
                    'Menlo',
                    'Monaco',
                    'Roboto Mono',
                    'Courier New',
                    'monospace',
                ],
                // design tokens
                'title-md': ['Inter'],
                'display-lg': ['Inter'],
                'display-mega': ['Inter'],
                'label-caps': ['Inter'],
                'display-md': ['Inter'],
                'display-sm': ['Inter'],
                'body-sm': ['Inter'],
                'display-xl': ['Inter'],
                'body-md': ['Inter'],
                'metrics-mono': ['JetBrains Mono'],
                'button-label': ['Inter'],
            },
            spacing: {
                xl: '32px',
                lg: '24px',
                xxs: '4px',
                sm: '12px',
                base: '16px',
                section: '96px',
                xs: '8px',
                xxl: '48px',
                md: '20px'
            },
            fontSize: {
                'title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
                'display-lg': ['36px', { lineHeight: '1.15', letterSpacing: '-1.08px', fontWeight: '600' }],
                'display-mega': ['64px', { lineHeight: '1.05', letterSpacing: '-1.92px', fontWeight: '600' }],
                'label-caps': ['11px', { lineHeight: '1.4', letterSpacing: '0.88px', fontWeight: '600' }],
                'display-md': ['28px', { lineHeight: '1.2', letterSpacing: '-0.84px', fontWeight: '600' }],
                'display-sm': ['22px', { lineHeight: '1.25', letterSpacing: '-0.5px', fontWeight: '600' }],
                'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
                'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-1.44px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
                'metrics-mono': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
                'button-label': ['14px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '500' }]
            },
            borderRadius: {
                none: '0px',
                xs: '4px',
                sm: '6px',
                md: '8px',
                lg: '12px',
                xl: '16px',
                xxl: '24px',
                pill: '9999px',
                full: '9999px',
            },
        },
    },
    plugins: [],
};
