/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.jsx',
        './resources/**/*.ts',
        './resources/**/*.tsx',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            colors: {
                primary: '#000000',
                'primary-active': '#1a1a1a',
                'text-link': '#0d74ce',
                ink: '#171717',
                body: '#60646c',
                'body-strong': '#171717',
                muted: '#999999',
                'muted-soft': '#cccccc',
                hairline: '#f0f0f3',
                'hairline-soft': '#f5f5f7',
                'hairline-strong': '#dcdee0',
                canvas: '#ffffff',
                'canvas-soft': '#fafafa',
                'surface-card': '#ffffff',
                'surface-strong': '#f0f0f3',
                'surface-dark': '#171717',
                'surface-dark-elevated': '#1a1a1a',
                'on-primary': '#ffffff',
                'on-dark': '#ffffff',
                'on-dark-soft': '#b0b4ba',
                'gradient-sky-light': '#cfe7ff',
                'gradient-sky-mid': '#a8c8e8',
                'accent-warning': '#ab6400',
                'accent-preview': '#8145b5',
                'accent-link-bright': '#47c2ff',
                'semantic-error': '#eb8e90',
                'semantic-success': '#16a34a',
            },
            fontFamily: {
                sans: [
                    'Figtree',
                    'Inter',
                    '-apple-system',
                    'system-ui',
                    'Segoe UI',
                    'Roboto',
                    'Helvetica',
                    'Arial',
                    'sans-serif',
                ],
                mono: [
                    'JetBrains Mono',
                    'ui-monospace',
                    'SFMono-Regular',
                    'Menlo',
                    'Monaco',
                    'Roboto Mono',
                    'Courier New',
                    'monospace',
                ],
            },
            borderRadius: {
                none: '0px',
                xs: '4px',
                sm: '6px',
                md: '8px',
                lg: '12px',
                xl: '16px',
                xxl: '24px',
                pill: '9999px',
                full: '9999px',
            },
        },
    },
    plugins: [],
};
